"""empty message

Revision ID: 2a808c7b3eca
Revises: 8c7e7b1eadf7
Create Date: 2019-07-07 23:53:17.525365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a808c7b3eca'
down_revision = '8c7e7b1eadf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date_create', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('events', sa.Column('starting_date', sa.String(length=255), nullable=False))
    op.drop_column('events', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('events', 'starting_date')
    op.drop_column('events', 'date_create')
    # ### end Alembic commands ###
