"""empty message

Revision ID: ee7e6a138b37
Revises: 0d7bb2055938
Create Date: 2019-07-06 23:12:42.178059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7e6a138b37'
down_revision = '0d7bb2055938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('date_purchase', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'date_purchase')
    # ### end Alembic commands ###
