"""empty message

Revision ID: f2e8c4bf88dc
Revises: e5cf84b92c75
Create Date: 2019-07-08 17:13:15.411178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e8c4bf88dc'
down_revision = 'e5cf84b92c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('purchases', sa.Column('ticket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchases', 'ticket', ['ticket_id'], ['ticket_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'ticket_id')
    op.drop_table('ticket')
    # ### end Alembic commands ###
